name: 'setup VTest'
description: 'ssss'

runs:
  using: "composite"
  steps:

    - name: Setup coredumps
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      shell: sh
      run: |
        sudo sysctl -w fs.suid_dumpable=1
        sudo sysctl kernel.core_pattern=/tmp/core.%h.%e.%t

    - name: Setup ulimit for core dumps
      shell: sh
      run: |
        # This is required for macOS which does not actually allow to increase
        # the '-n' soft limit to the hard limit, thus failing to run.
        ulimit -n 65536
        ulimit -c unlimited

    - name: Get VTest latest commit SHA
      id: vtest-sha
      shell: sh
      run: |
        echo "sha=$(git ls-remote https://code.vinyl-cache.org/vtest/VTest2 HEAD | cut -f1)" >> $GITHUB_OUTPUT

    - name: Cache VTest
      id: cache-vtest
      uses: actions/cache@v5
      with:
        path: ${{ github.workspace }}/vtest
        key: vtest-${{ runner.os }}-${{ runner.arch }}-${{ steps.vtest-sha.outputs.sha }}

    - name: Install VTest
      if: ${{ steps.cache-vtest.outputs.cache-hit != 'true' }}
      shell: sh
      run: |
        DESTDIR=${{ github.workspace }}/vtest scripts/build-vtest.sh

    - name: Install problem matcher for VTest
      shell: sh
      # This allows one to more easily see which tests fail.
      run: echo "::add-matcher::.github/vtest.json"



