name: Contrib

on:
  push:

permissions:
  contents: read

jobs:
  compile:
    name: ${{ matrix.name }}
    runs-on: ubuntu-slim
    strategy:
      matrix:
        include:
        - name: admin/halog/
          targets:
          - admin/halog/halog
        - name: dev/flags/
          targets:
          - dev/flags/flags
        - name: dev/haring/
          targets:
          - dev/haring/haring
        - name: dev/hpack/
          targets:
          - dev/hpack/decode
          - dev/hpack/gen-enc
          - dev/hpack/gen-rht
        - name: dev/poll/
          targets:
          - dev/poll/poll
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
    - run: make ${{ join(matrix.targets, ' ') }}
